### ISSUE TITLE
Sintáxis/Código

### ISSUE THREAD

**Issue by lucasjaviluna** [francobidart/dsw-tp-frontend#1]
[Low]
	- Este modulo no tiene nada https://vscode.dev/github/francobidart/dsw-tp-frontend/blob/main/src/app/vista-producto/vista-producto.module.ts
	- Está desaconsejado el uso de var https://vscode.dev/github/francobidart/dsw-tp-frontend/blob/main/src/app/usuarios/usuarios.component.ts#L37
	- Este routing no tiene nada https://vscode.dev/github/francobidart/dsw-tp-frontend/blob/main/src/app/app-routing.module.ts#L10
	- En muchos componentes hay métodos del ciclo de vida que están vacíos. Ej: https://vscode.dev/github/francobidart/dsw-tp-frontend/blob/main/src/app/registrarse/registrarse.component.ts#L16

**Comment by francobidart** [comment]
Buenas tardes, se implementaron los cambios solicitados:

- Este modulo no tiene nada vista-producto.module.ts | Módulo no utilizado, **eliminado**
- Está desaconsejado el uso de var usuarios.component.ts | Variable no utilizada, **eliminada**
- Este routing no tiene nada app-routing.module.ts | **Eliminado** en issue previa 

- En muchos componentes hay métodos del ciclo de vida que están vacíos. | Se revisaron los componentes que no realizaban acciones durante su inicialización, posteriormente se eliminó la implementación de onInit en los que correspondían.

_En relación a este último cambio, el origen de que estos metodos se encontraran vacios pero implementados fue debido a que al generar un componente desde angular-cli estos se crean implementando OnInit por defecto._


COMMIT: https://github.com/francobidart/dsw-tp-frontend/commit/352b36f740f5d6a7ce42cad478a41fa83fc748f0
