### ISSUE TITLE
Módulos

### ISSUE THREAD

**Issue by lucasjaviluna** [francobidart/dsw-tp-frontend#3]
[Middle]
	- Todos los paths de admin se podrían haber agrupado en un módulo exclusivo para Admin. De esa manera, se evita tener todas las rutas en un solo archivo, y se divide mejor la responsabilidad de cada módulo.
	https://vscode.dev/github/francobidart/dsw-tp-frontend/blob/main/src/app/app.module.ts#L117

**Comment by francobidart** [comment]
Buenas tardes profesor.

De acuerdo a lo solicitado, se agrega el AppAdminModule, que contiene las rutas e imports necesarios para el correcto funcionamiento del módulo administrador.

COMMIT: https://github.com/francobidart/dsw-tp-frontend/commit/86a285568ccfd924564b95b2d7efee3c948ebf95
