### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by lucasjaviluna** [francobidart/dsw-tp-frontend#4]
[Middle]
	- En muchos lugares se usan estilos inline. Esto está desaconsejado debido a que dificulta la mantenibilidad y la legibilidad del código.
	Lo mejor es usar clases y reutilizarlas en los template
	Ej: https://vscode.dev/github/francobidart/dsw-tp-frontend/blob/main/src/app/usuarios/usuarios.component.html#L21

**Comment by francobidart** [comment]
Buenas noches profesor.

Conforme a lo solicitado, se movieron los estilos a clases para mejorar el mantenimiento.

En algunos casos (por ejemplo, la alineación del texto en la última columna de las tablas) se no se modificó el comportamiento.

COMMIT: https://github.com/francobidart/dsw-tp-frontend/commit/e90eb978a93e75cc8659b85df5694ec7a2532d82
