### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by lucasjaviluna** [francobidart/dsw-tp-frontend#5]
[Low]
	- La mayoría de los métodos de servicios que llaman a la api, no especifican el tipo de retorno o bien usan any, lo cual no aprovecha los beneficios de typescript

**Comment by francobidart** [comment]
En relación a este tema tuvimos algunas dudas sobre como sería posible de implementar. Nuestra api realiza una respuesta por defecto con el siguiente formato:

{
  "status": "OK",
  "mensaje": "",
  "total_resultados": 0,
  "resultados": [] (Este array puede contener 0 a n instancias de una entidad)
}

No estamos seguros de cómo implementar esta estructura correctamente en el código.

**Comment by lucasjaviluna** [comment]
Hola, si la API responde eso, entonces podrían mapearlo con una interface:
export interface ModelResponse<T> {
  status: string;
  mensaje: string;
  total_resultados: number;
  resultados: T[];
}

Supongamos que Entity representa una entity User, que tiene la forma: { name: string, lastName: string }, entonces tendríamos:
interface User {
  name: string;
  lastName: string;
}

y luego lo usarían como ModelResponse<User>, de esa manera el generic T se reemplaza por la entity User y se mantiene la uniformidad en la respuesta

**Comment by francobidart** [comment]
Buenas tardes profesor.

Ya se encuentran subidos los cambios requeridos conforme a lo indicado.

NOTA: Se mantuvo la estructura actual para el servicio de login, ya que no devuelve una entidad sino una serie de atributos personalizados que no se encuentran dentro de un array.

COMMIT: https://github.com/francobidart/dsw-tp-frontend/commit/f173e1bde042093205b5b8f88b2945754cbd6e2c
