### ISSUE TITLE
Deprecaciones

### ISSUE THREAD

**Issue by lucasjaviluna** [francobidart/dsw-tp-frontend#6]
[High]
	- En varios lugares se usa una forma de subscribe() que está deprecada. 
	Ej: https://vscode.dev/github/francobidart/dsw-tp-frontend/blob/main/src/app/detalle-pedido/detalle-pedido.component.ts#L27
	Reemplazarlo usando el callback object con los atributos next, error y complete, según corresponda https://rxjs.dev/deprecations/subscribe-arguments

**Comment by francobidart** [comment]
Buenas tardes profesor,

Ya fueron realizadas las modificaciones en componentes y servicios para cumplir con lo indicado por la documentación.

COMMIT: https://github.com/francobidart/dsw-tp-frontend/commit/271ecd9e2009fb789d6a0b10156395f3948e2029
